# Generated by Django 5.0.1 on 2024-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
